// Seed reviews per product id: [name, city, date, rating, size, text]
window.QYRAH_REVIEWS = {
layla: [
["Ayesha K.","Hyderabad","2026-09-14",5,"S","Wore this for my brother's nikah and lost count of how many aunties asked where it was from. The gold embroidery on the sleeves looks even better in person."],
["Fathima R.","Kozhikode","2026-09-02",5,"M","Colour is exactly like the photos, a deep ruby, not the bright red I was worried about. Heavy fabric, falls really nicely."],
["Sana M.","Mumbai","2026-08-27",4,"S","Beautiful piece. Took a little longer to arrive than I expected but the team kept me updated on WhatsApp the whole time."],
["Noor A.","Dubai","2026-08-19",5,"L","Asked for a length adjustment since I'm 5'2. It came perfect, didn't have to do anything. The cape sleeves move so beautifully when you walk."],
["Hiba S.","Bengaluru","2026-08-11",5,"M","Honestly the best abaya I own now. Stitching inside is as neat as outside, you can tell it's made with care."],
["Zainab F.","Lucknow","2026-08-03",4,"S","Gorgeous but on the heavier side, so maybe not for a long summer day outdoors. For evening functions it's perfect."],
["Mariam T.","Doha","2026-07-26",5,"M","Bought it for Eid. My husband said it's the first abaya he's actually noticed on me lol. Embroidery is very fine, not loud."],
["Rukhsar B.","Delhi","2026-07-18",5,"S","Even the packaging felt special. And the abaya — no words. Worth every rupee."],
["Aaliya N.","Chennai","2026-07-09",5,"M","Was confused between S and M, messaged them and they asked my height and shoulder and suggested M. Fits exactly right."],
["Shireen P.","Pune","2026-06-30",4,"L","Lovely quality. Sleeves are quite wide so I wear a fitted inner with it. Just something to keep in mind."],
["Humaira J.","Srinagar","2026-06-21",5,"M","Got so many compliments at a wedding. The colour photographs beautifully too."],
["Amna Q.","Sharjah","2026-06-12",5,"S","Second piece I've bought from Qyrah. Consistent quality, and the ruby is really rich."],
["Safa H.","Kochi","2026-06-01",5,"M","Very elegant. The embroidery is only on the sleeves and edges so it still feels modest."],
["Nida Z.","Hyderabad","2026-05-24",3,"S","The abaya itself is lovely. Delivery got delayed by about a week because of the embroidery, I wish I'd known the timeline upfront. Would still recommend."],
["Iqra D.","Muscat","2026-05-15",5,"L","My mother wore this for my wedding and she looked so graceful. We're both very happy."],
["Farah S.","Bengaluru","2026-05-06",5,"M","Feels like something from a boutique in Dubai. Gold thread hasn't lost any shine after a few wears."],
["Tasneem K.","Mumbai","2026-04-22",4,"S","Really pretty. Creased a bit on the way, a quick steam fixed it."],
["Laiba R.","Riyadh","2026-04-10",5,"M","Perfect for occasions. Classy without trying too hard."]
],
hessa: [
["Rabia S.","Srinagar","2026-09-10",5,"M","Perfect for our winters. The velvet is thick and soft and the colour is like wine. Felt like royalty wearing it."],
["Mehwish A.","Delhi","2026-08-30",5,"S","Velvet quality is really good, not the shiny cheap kind. It has that nice deep pile."],
["Anam K.","Lucknow","2026-08-16",4,"M","Absolutely stunning but warm, so I'd say it's more of a winter or AC-venue abaya."],
["Shabnam R.","Hyderabad","2026-08-04",5,"L","Wore it to a walima dinner. The embroidery on the cuffs is subtle and so pretty up close."],
["Sumaiya T.","Dubai","2026-07-20",5,"M","I was nervous ordering velvet online but it's even nicer than the photos. The lining makes it slide on easily."],
["Ruqayya M.","Bengaluru","2026-07-05",4,"S","Lovely. Picks up a bit of lint so keep a lint roller handy, but that's velvet for you."],
["Kulsum N.","Mumbai","2026-06-22",5,"M","The fall is so graceful. Doesn't feel bulky at all even though it's velvet."],
["Afreen J.","Chennai","2026-06-08",5,"S","Bought it as a gift for my sister-in-law. She video called me just to show it off."],
["Nazia H.","Doha","2026-05-27",5,"L","Rich colour, great stitching, and the team was so sweet on WhatsApp."],
["Sadia B.","Pune","2026-05-12",3,"M","Beautiful but a little long for me at 5'1. Should have asked for a length adjustment. They offered to help after, which I appreciated."],
["Maryam F.","Kozhikode","2026-04-29",5,"S","Nothing else in my wardrobe feels this luxurious."],
["Asma Y.","Sharjah","2026-04-14",5,"M","Wore it to an evening event, got asked where it's from at least five times."],
["Heena P.","Delhi","2026-03-30",4,"L","Gorgeous. A bit heavier than I expected, but it drapes really well because of that."],
["Uzma L.","Hyderabad","2026-03-18",5,"M","Worth it. Handle with care and it will last years."]
],
amira: [
["Zoya K.","Mumbai","2026-09-08",5,"S","The pleats! It moves like water when you walk. I keep twirling in it like a kid."],
["Bushra M.","Bengaluru","2026-08-24",5,"M","Light enough for Mumbai weather, which I didn't expect from something this dressy."],
["Samreen A.","Hyderabad","2026-08-09",4,"M","Really lovely. The pleats need a bit of care when washing, I hand wash and hang it and it's fine."],
["Hafsa R.","Dubai","2026-07-29",5,"L","Flattering on every body type I think. It's very generous, doesn't cling anywhere."],
["Areeba S.","Delhi","2026-07-12",5,"S","Wore it for Eid and it photographed so well. Colour is rich without being too bright."],
["Nusrat J.","Kochi","2026-06-27",5,"M","Soft sheen, beautiful fall, excellent finishing on the hem."],
["Aisha Z.","Lucknow","2026-06-10",4,"S","Loved it, just wish it had pockets!"],
["Mahnoor T.","Doha","2026-05-28",5,"M","I'm usually in black abayas so this was a big step for me. So glad I did it."],
["Yusra B.","Chennai","2026-05-14",5,"L","Great quality and it came nicely packed with a little handwritten note. Small things matter."],
["Arshiya N.","Pune","2026-04-30",3,"M","The abaya is lovely but on my screen the colour looked brighter. In person it's a deeper red. Still nice, just not what I pictured."],
["Faiza Q.","Muscat","2026-04-15",5,"S","Elegant and easy. Works with flats or heels."],
["Sameera H.","Hyderabad","2026-03-28",5,"M","Excellent. My mother ordered one too after seeing mine."]
],
yasmin: [
["Dr. Salma I.","Bengaluru","2026-09-12",5,"M","Finally an abaya I can wear to the hospital and to conferences. Looks structured and professional."],
["Nazneen K.","Dubai","2026-08-25",5,"S","The lapel makes it feel like a coat. Very sharp. Fits true to size."],
["Rumana S.","Mumbai","2026-08-07",4,"M","Smart and well made. Shoulders are a bit structured, so if you like very soft abayas this may not be for you."],
["Ifrah A.","Delhi","2026-07-21",5,"L","Wore it for a work presentation and felt super confident."],
["Mehreen H.","Hyderabad","2026-07-03",5,"M","Tailoring is spot on. The lining is soft and doesn't make you sweat."],
["Shazia P.","Doha","2026-06-15",5,"S","Classy. Doesn't look like a typical abaya at all, more like something from a designer store."],
["Tahira M.","Chennai","2026-05-30",4,"M","Really nice. I sized up for layering in winter like the description said, good call."],
["Afshan R.","Riyadh","2026-05-11",5,"L","Great for office. Colour is deep and rich."],
["Lubna Z.","Pune","2026-04-26",5,"S","Arrived quickly and the fit is perfect."],
["Sabiha N.","Lucknow","2026-04-08",3,"M","Lovely piece but the concealed buttons took me some getting used to. Fabric and colour are great."],
["Kiran F.","Sharjah","2026-03-22",5,"M","One of my best purchases this year."]
],
noor: [
["Alina M.","Kochi","2026-09-16",5,"S","So fresh and pretty. Wore it to a daytime nikah and it was perfect in the heat."],
["Sara K.","Hyderabad","2026-09-01",5,"M","The black piping on the sleeves is such a nice touch, makes the print look modern."],
["Hina R.","Mumbai","2026-08-18",4,"S","Lovely print. It's a bit sheer so I wear a light slip underneath."],
["Fariha A.","Bengaluru","2026-08-05",5,"M","The tiered sleeves are my favourite part. Feels so feminine."],
["Aqsa S.","Dubai","2026-07-23",5,"L","Soft, flowy and the colours are gentle, not loud like most floral abayas."],
["Nimra J.","Delhi","2026-07-08",5,"S","Bought it for summer Eid, it was the lightest thing I wore all day."],
["Sidra T.","Chennai","2026-06-24",4,"M","Beautiful. Ivory needs careful handling though, I got mehndi on the cuff within an hour lol."],
["Muskan B.","Lucknow","2026-06-09",5,"M","Such a dreamy piece. My friends are all asking for the link."],
["Anum H.","Doha","2026-05-26",5,"S","Print quality is excellent, very crisp, no fading after washing."],
["Rida Q.","Pune","2026-05-10",5,"L","Exactly as pictured."],
["Aleena N.","Kozhikode","2026-04-27",5,"M","Wore it for my daughter's aqeeqah. Looked so elegant in the pictures."],
["Shifa Z.","Muscat","2026-04-12",3,"S","Nice abaya, but I'd prefer it slightly more opaque. Delivery was quick."],
["Mahira F.","Hyderabad","2026-03-29",5,"M","Light as air. Love it."]
],
reem: [
["Hania S.","Dubai","2026-09-18",5,"M","The embroidery is breathtaking. Every rose is so detailed, you can see the hand work."],
["Shaista K.","Hyderabad","2026-09-05",5,"S","Wore it for a family wedding. The dark base with soft pink roses looks so classy at night."],
["Adeeba R.","Mumbai","2026-08-22",5,"L","My favourite from the collection. Photos don't do it justice."],
["Zehra A.","Bengaluru","2026-08-10",4,"M","Absolutely beautiful. Embroidery is heavy on the sleeves so it's a little weighty there, but it's worth it."],
["Inaya M.","Delhi","2026-07-30",5,"S","Received so many compliments. The fall is lovely too."],
["Bisma T.","Srinagar","2026-07-17",5,"M","Reminds me of the old kashida work my nani used to do. Very special."],
["Sumbul J.","Doha","2026-07-04",5,"M","Such quality. I checked the inside and even the back of the embroidery is neat."],
["Nadia H.","Lucknow","2026-06-20",4,"L","Stunning. Had to steam it after delivery, it creased a bit in transit."],
["Amreen S.","Chennai","2026-06-07",5,"S","Graceful and modest. My mother-in-law approved, which says a lot."],
["Rehana B.","Kochi","2026-05-25",5,"M","Beautiful for Eid. It's a deep midnight, almost black indoors, lovely in daylight."],
["Saba N.","Riyadh","2026-05-13",5,"M","Ordered two, one for me and one for my sister. We both love it."],
["Kainat F.","Pune","2026-04-30",3,"S","The abaya is beautiful but it took almost 3 weeks to arrive. The team was responsive though."],
["Arfa Z.","Sharjah","2026-04-18",5,"L","A real statement piece but still elegant."],
["Madiha Q.","Hyderabad","2026-04-05",5,"M","Perfect."],
["Taiba R.","Mumbai","2026-03-24",5,"S","Exactly what I was looking for for a reception. So happy."],
["Shaheen A.","Delhi","2026-03-12",4,"M","Love it. Slightly long for me, I'll get it hemmed an inch."]
],
samar: [
["Noorin K.","Bengaluru","2026-09-11",5,"M","Grey is such an underrated colour. This one is soft and calm, and the lilies are so delicate."],
["Afia S.","Hyderabad","2026-08-28",5,"S","I wear it to work at least once a week. Easy, comfortable, pretty."],
["Ramsha A.","Dubai","2026-08-12",4,"M","Lovely everyday abaya. Wish it came in a darker charcoal as well."],
["Hira M.","Mumbai","2026-07-27",5,"L","The embroidery on the sleeves is very fine and doesn't catch on anything."],
["Ummehani T.","Lucknow","2026-07-11",5,"M","Very comfortable, not heavy at all. The closed front is great for college."],
["Nazish R.","Delhi","2026-06-25",5,"S","Soft fabric, good length, pretty detail. Can't ask for more."],
["Seher J.","Kochi","2026-06-11",4,"M","Great quality. The grey is a little lighter than the photos in daylight."],
["Almas B.","Chennai","2026-05-29",5,"M","Wore it to my cousin's mehendi and felt understated in a good way."],
["Sanober F.","Doha","2026-05-16",5,"L","Hand washed it twice, still looks new."],
["Maheen H.","Pune","2026-05-02",5,"S","Subtle and elegant. Exactly my style."],
["Fiza N.","Hyderabad","2026-04-17",3,"M","Pretty, but I found the sleeves a bit narrow for layering a cardigan."],
["Rukaiya Z.","Muscat","2026-04-01",5,"M","Beautiful work on the lilies. Great value."]
],
nada: [
["Alisha K.","Hyderabad","2026-09-15",5,"M","The butterfly cut is so flattering and so easy to wear. Felt like a princess on Eid."],
["Mahjabeen S.","Dubai","2026-09-03",5,"M","The satin is smooth and cool on the skin. The peonies are gorgeous."],
["Rabiya A.","Mumbai","2026-08-21",5,"S","Wore it to an Eid lunch and my whole family wanted one."],
["Fatima Z.","Bengaluru","2026-08-08",4,"L","Beautiful and flowy. It slips a little off the shoulders so I pin it in place."],
["Nawal H.","Doha","2026-07-25",5,"M","The print is so rich and the satin has a soft sheen, not too shiny."],
["Sumayya R.","Kozhikode","2026-07-13",5,"M","Such a feminine piece. Photographs beautifully."],
["Laila J.","Delhi","2026-06-29",5,"S","Easy to wear, and it looks like I made an effort even when I didn't."],
["Imaan T.","Chennai","2026-06-16",4,"M","Really pretty. Satin shows water marks so be careful with drinks."],
["Neha M.","Pune","2026-06-02",5,"L","Bought it as an Eid gift for my mum. She loves it."],
["Maisa B.","Lucknow","2026-05-20",5,"S","The butterfly cut suits me so well, never thought it would."],
["Aroosa N.","Srinagar","2026-05-07",5,"M","Colours are vibrant but still soft. Great finishing."],
["Qurat F.","Sharjah","2026-04-24",3,"M","Pretty, but it moves around a lot, I prefer a more fitted style. Quality is good though."],
["Shumaila K.","Hyderabad","2026-04-09",5,"S","Loved it for our Eid photos!"],
["Dania A.","Riyadh","2026-03-27",5,"L","Stunning, flowy and comfortable in the heat."],
["Rimsha S.","Mumbai","2026-03-15",5,"M","Everything about it is lovely."]
],
dana: [
["Nafisa K.","Hyderabad","2026-09-17",5,"M","The beadwork only shows when the light catches it. So subtle and classy."],
["Mehak S.","Bengaluru","2026-09-06",5,"S","My go-to black abaya now. The fabric is soft and matte and doesn't show dust."],
["Samia A.","Dubai","2026-08-26",5,"L","Simple enough for daily wear, but the sleeves make it special."],
["Tabassum R.","Mumbai","2026-08-14",4,"M","Good quality. A couple of beads came loose after a month and the team told me how to fix it. Otherwise great."],
["Anisa J.","Delhi","2026-08-01",5,"S","Classic black done well. The skirt is full and flows nicely."],
["Husna M.","Lucknow","2026-07-19",5,"M","Very comfortable and breathable. I wear it to university."],
["Aafreen B.","Chennai","2026-07-06",5,"M","Perfect length for me at 5'5 in size M."],
["Nishat T.","Kochi","2026-06-23",5,"L","Neat stitching, lovely detailing."],
["Suha F.","Doha","2026-06-10",4,"S","Beautiful, but the sleeves are wide so be careful in the kitchen haha."],
["Sadaf H.","Pune","2026-05-28",5,"M","Ordered after seeing it on a friend. Just as good in person."],
["Nargis Z.","Srinagar","2026-05-15",5,"M","Excellent quality black, hasn't faded."],
["Ilham N.","Muscat","2026-05-01",5,"S","Elegant and simple. Exactly my taste."],
["Zubia A.","Hyderabad","2026-04-19",5,"L","My mother loved hers so I got one too."],
["Areej K.","Sharjah","2026-04-06",3,"M","Nice abaya but it attracts a little lint. The beadwork is pretty."],
["Gulnaz S.","Delhi","2026-03-26",5,"M","Great price for this quality."],
["Mariya R.","Bengaluru","2026-03-14",5,"S","Simple, beautiful, well made."],
["Hadiya P.","Mumbai","2026-03-03",4,"M","Really nice. Took about a week to arrive."]
],
mira: [
["Shabana K.","Hyderabad","2026-09-19",5,"M","Most comfortable abaya I own. The linen-feel fabric breathes so well in this heat."],
["Rafia S.","Chennai","2026-09-09",5,"L","I wear it almost every day. The belt gives it shape without making it tight."],
["Mubeena A.","Kozhikode","2026-08-29",5,"S","Washes really well in the machine on gentle. Such a relief for a daily abaya."],
["Nausheen R.","Mumbai","2026-08-17",4,"M","Very practical and neat. Creases a bit because of the linen texture, but that's expected."],
["Firdaus J.","Bengaluru","2026-08-06",5,"M","Perfect for office. Looks put together with zero effort."],
["Shagufta M.","Delhi","2026-07-24",5,"L","Bought two, one to wear and one to keep packed for travel."],
["Amatullah T.","Lucknow","2026-07-14",5,"S","So easy. I throw it on for school runs and still look neat."],
["Kausar B.","Hyderabad","2026-07-02",5,"M","Lovely matte black, and the pleats from the waist are so flattering."],
["Rizwana F.","Pune","2026-06-19",4,"M","Good everyday abaya. Belt loops could be a little stronger."],
["Sahar H.","Dubai","2026-06-07",5,"S","Great for the Dubai summer. Doesn't cling."],
["Yasmeen N.","Doha","2026-05-26",5,"M","Very good value for daily wear."],
["Bilqis Z.","Chennai","2026-05-13",5,"L","Soft, light, and doesn't show sweat marks."],
["Nabila A.","Mumbai","2026-05-01",5,"S","Clean, simple, modern. Love the belt."],
["Munira K.","Srinagar","2026-04-20",3,"M","Comfortable, but the black felt a little flat compared to my other abayas. Good for daily use."],
["Sajida R.","Bengaluru","2026-04-08",5,"M","Confirmed on a Monday and it arrived by Friday. Fits perfectly."],
["Tahseen S.","Delhi","2026-03-28",5,"L","My daily uniform now."],
["Farheen M.","Hyderabad","2026-03-17",5,"S","Great fabric, no pilling so far."],
["Asiya T.","Kochi","2026-03-06",4,"M","Nice. The belt is a bit long for me, I just wrap it twice."],
["Zareen B.","Muscat","2026-02-24",5,"M","Simple and beautiful."]
],
huda: [
["Arifa K.","Hyderabad","2026-09-13",5,"M","The satin trim gives it just enough shine. Looks polished for work and for dinners."],
["Nasreen S.","Dubai","2026-08-31",5,"S","Very light crepe, and it doesn't wrinkle much, which is great for travel."],
["Humna A.","Mumbai","2026-08-15",4,"M","Lovely. The satin trim needs a cool iron, learnt that the hard way."],
["Ayat R.","Bengaluru","2026-08-02",5,"L","Simple but so elegant. My sister borrowed it and still hasn't returned it."],
["Sobia J.","Delhi","2026-07-18",5,"M","The tapered sleeves are great, they don't get in the way."],
["Mahek T.","Chennai","2026-07-03",5,"S","Good quality black crepe, drapes well."],
["Tuba M.","Lucknow","2026-06-18",5,"M","Good length and fit. The belt is a nice touch."],
["Sania F.","Doha","2026-06-04",4,"L","Nice, but I'd have loved the trim in a contrasting colour too."],
["Irum H.","Pune","2026-05-21",5,"M","Perfect everyday abaya with a little something extra."],
["Nudrat B.","Kozhikode","2026-05-08",5,"S","Came with a thank-you card. The abaya is lovely."],
["Hafeeza Z.","Hyderabad","2026-04-23",5,"M","Comfortable and chic."],
["Rubina N.","Riyadh","2026-04-10",3,"L","Fabric is nice but a bit thinner than I expected. Would be great for summer."],
["Zara A.","Mumbai","2026-03-29",5,"S","Clean lines, great finishing. Very happy."]
],
salma: [
["Aminah K.","Dubai","2026-09-16",5,"M","It floats! The layers move so beautifully, I felt so graceful walking in it."],
["Sabeena S.","Hyderabad","2026-09-04",5,"S","Light and airy, but the inner layer means it isn't see-through at all."],
["Rehma A.","Mumbai","2026-08-20",4,"M","Gorgeous, but georgette snags easily, so avoid bracelets with hooks."],
["Parveen R.","Bengaluru","2026-08-07",5,"L","I get compliments every single time I wear it."],
["Hoorain J.","Delhi","2026-07-26",5,"M","Perfect for summer weddings, stays cool."],
["Warda T.","Chennai","2026-07-10",5,"S","The bell sleeves are dreamy."],
["Qamar M.","Lucknow","2026-06-26",5,"M","Elegant, flowy, modest. Everything I wanted."],
["Minahil F.","Doha","2026-06-12",4,"M","Beautiful. A little long for me, I'm getting it shortened."],
["Suhana H.","Kochi","2026-05-30",5,"L","Soft and graceful. With heels it's stunning."],
["Anousha B.","Pune","2026-05-17",5,"S","Lovely quality for the price."],
["Durdana Z.","Srinagar","2026-05-03",5,"M","Beautiful on its own, doesn't need any jewellery."],
["Hibba N.","Sharjah","2026-04-20",3,"M","Pretty, but the layers tangle a bit when you sit. Takes some getting used to."],
["Kashaf A.","Hyderabad","2026-04-06",5,"S","My favourite for evenings."],
["Rabab K.","Mumbai","2026-03-23",5,"L","Airy and elegant."]
],
sahar: [
["Alfiya K.","Hyderabad","2026-09-20",5,"S","Wore it for my own nikah. I've never felt more beautiful. The lace work on the back is incredible."],
["Mehnaz S.","Dubai","2026-08-30",5,"M","The blush is so soft and romantic. The satin is thick and structured and feels very expensive."],
["Nuzhat A.","Mumbai","2026-08-13",5,"M","They took my measurements on WhatsApp and it fit perfectly. Worth the wait."],
["Sabahat R.","Bengaluru","2026-07-28",4,"S","Beautiful. It's made to order, so plan ahead — mine took about 3 weeks."],
["Ghazala J.","Delhi","2026-07-09",5,"L","My daughter wore it for her engagement. Everyone was asking about it."],
["Farzana T.","Kozhikode","2026-06-21",5,"M","You can tell the lace is placed by hand. Stunning finish."],
["Mahrukh M.","Doha","2026-06-02",5,"S","Absolutely worth it for a once-in-a-lifetime occasion."],
["Shazmeen F.","Lucknow","2026-05-15",5,"M","The photos from the reception came out like a magazine."],
["Najma H.","Chennai","2026-04-27",4,"L","Gorgeous but on the heavier side for a long day. For a few hours it's perfect."],
["Alvina B.","Pune","2026-04-08",5,"S","Elegant, modest and bridal all at once."],
["Umaima Z.","Riyadh","2026-03-19",5,"M","Dream abaya."]
],
lulwa: [
["Rukhsana K.","Hyderabad","2026-09-09",5,"M","I wear it to court. Looks sharp and professional, and the lapels are beautiful."],
["Samina S.","Dubai","2026-08-22",5,"S","The structured shoulders make it look like a proper coat. Love the wrap front."],
["Tehreem A.","Mumbai","2026-08-04",4,"M","Very well tailored. Takes 2–3 weeks since it's made to order."],
["Anbreen R.","Bengaluru","2026-07-16",5,"L","I feel so confident in this for meetings."],
["Shehla J.","Delhi","2026-06-28",5,"M","Tailoring is excellent, the fit is exact to my measurements."],
["Adiba T.","Doha","2026-06-09",5,"S","Timeless. Wore it to my graduation too."],
["Nusaiba M.","Chennai","2026-05-21",4,"M","Very smart. A little warm for summer afternoons."],
["Sarwat F.","Lucknow","2026-05-02",5,"L","Best black abaya for work I've found."],
["Hameeda H.","Pune","2026-04-14",5,"M","Clean, powerful look."],
["Mishal B.","Sharjah","2026-03-26",5,"S","Excellent quality. Worth it."]
],
zahra: [
["Ifra K.","Hyderabad","2026-09-18",5,"M","The emerald is so rich, it looks like a jewel. Wore it to a walima and got so many compliments."],
["Shanza S.","Dubai","2026-09-02",5,"S","The wrap style is so flattering, and the side tie makes it easy to adjust."],
["Roshni A.","Mumbai","2026-08-19",5,"M","Never owned a green abaya before. Now I want every colour."],
["Hamna R.","Bengaluru","2026-08-03",4,"L","Lovely colour, and the matte crepe drapes nicely. It's made to order so give it a couple of weeks."],
["Saima J.","Delhi","2026-07-15",5,"M","Such a beautiful colour, in daylight and indoors."],
["Mashal T.","Kochi","2026-06-27",5,"S","The shawl collar is so elegant."],
["Rumaisa M.","Lucknow","2026-06-08",5,"M","Perfect fit, they made it exactly to my measurements."],
["Nabeela F.","Doha","2026-05-20",4,"M","Gorgeous. The belt is long so I tie it twice."],
["Ayesha B.","Chennai","2026-05-02",5,"L","Looked stunning at an Eid dinner."],
["Anam H.","Pune","2026-04-14",5,"S","Absolutely love the colour."],
["Sabreen Z.","Muscat","2026-03-27",3,"M","Lovely, but the green was a bit darker than I imagined. Quality is great."],
["Maliha N.","Hyderabad","2026-03-10",5,"M","Classy and unique."]
],
aseel: [
["Zunaira K.","Dubai","2026-09-14",5,"M","The ombré is like a sunset. Such a dreamy abaya."],
["Haleema S.","Hyderabad","2026-08-27",5,"S","Light and airy, and the colour deepens so beautifully towards the hem."],
["Sehrish A.","Mumbai","2026-08-09",4,"M","Gorgeous. Dry clean only, so keep that in mind."],
["Mahwish R.","Bengaluru","2026-07-22",5,"L","Wore it to a beach nikah in Goa, it was perfect."],
["Izza J.","Delhi","2026-07-04",5,"M","Every photo of me in it looks like art."],
["Amal T.","Doha","2026-06-16",5,"S","Made to order and totally worth the wait."],
["Nigar M.","Lucknow","2026-05-29",5,"M","Beautiful dye work, very even."],
["Shafaq F.","Chennai","2026-05-11",4,"L","Lovely. I wish it came in another colour too."],
["Fareeha H.","Pune","2026-04-23",5,"M","So elegant and different."],
["Aiza B.","Kozhikode","2026-04-05",5,"S","Absolutely beautiful."]
]
};
